CREATE DATABASE OLA ;
USE OLA ;

CREATE TABLE OLA_1 
( 
  OLA_DATE INT , 
  OLA_DRIVERNAME  VARCHAR (60) ,
  OLA_DRIVERID INT , 
  OLA_PICKUP VARCHAR (60),
  OLA_DROPOFF VARCHAR (60),
  OLA_FARE INT ,
  OLA_PASSENGERID INT ,
  OLA_PASSENGERNAME VARCHAR (60),
  OLA_AVAILABLEVECHILE VARCHAR (60)
  );
  
SELECT * FROM OLA_1 ;
